### ISSUE TITLE
Create About, Contact and FAQ page

### ISSUE THREAD

**Issue by nitishragu12** [nitishragu12/CITS5505-GroupProject#10]
develop an about, contact and faq webpage for our webapp

**Comment by nitishragu12** [comment]
removed the need for contact page, merged it into about page

**Comment by iwhsajar** [comment]
okay sure will work on it

**Comment by ShaluSeeni** [comment]
Need to edit css layout for about page. will try working on it.

**Comment by nitishragu12** [comment]
modified about page css layout and created FAQ page
